movies/movieproject/movieapp/urls.py
from . import views
from django.urls import path
app_name='movieapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movieid>/',views.detail,name='detail'),
    path('add/',views.addmovie,name='addmovie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),
]

movies/movieproject/movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movies/movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=100)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movies/movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import Movie
from . form import MovieForm
# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={'movie_list':movie}
    return render(request,'index.html',context)

def detail(request,movieid):
    movie=Movie.objects.get(id=movieid)

    return render(request,'detail.html',{'movie':movie})

def addmovie(request):
    if request.method=='POST':
        name=request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
    return render(request,'add.html')

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movies/movieproject/templates/add.html
{% extends 'base.html' %}

{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter the movie name"> <br><br>
    <input type="text" name="desc" placeholder="Enter the movie desc"> <br><br>
    <input type="text" name="year" placeholder="Enter the movie year"> <br><br>
    <input type="file" name="img"> <br>
    <input type="submit">
</form>

{% endblock %}

movies/movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>movie</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static   'style.css' %}">

</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="#">
    Movie site
  </a>
<a class="btn btn-update" align="right"  href="{% url 'movieapp:index'  %}">Home page</a>
</nav>
{% block body %}

{% endblock %}
</body>
</html>

movies/movieproject/templates/delete.html
{% extends 'base.html' %}

{% block body %}

<form method="post" >
  {% csrf_token %}

  do you want to delete?
  <input type="submit">
</form>
{% endblock %}

movies/movieproject/templates/detail.html
{% extends 'base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" height="400" width="500">
        </div>

    <div class="col-md-6">

        <h1>movie name :{{movie.name}}</h1>><br>
        <h3>released year :{{movie.year}}</h3>><br>
        <h2>Brief Description :{{movie.desc}}</h2>><br>
<a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">update</a>
<a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>
    </div>


    </div>
</div>

{% endblock %}

movies/movieproject/templates/edit.html
{% extends 'base.html' %}

{% block body %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">

</form>


{% endblock %}

movies/movieproject/templates/index.html
{% extends 'base.html' %}

{% block body %}

<div class="container" margin-left="10px">
    <div class="row">
        {% for i in movie_list %}


            <div class="card" style="width: 18rem; margin:20px; padding:5px;" >
  <img src="{{i.img.url}}" width="150" height="200" class="card-img-top" alt="...">
  <div class="card-body" >
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">movie details</a>
  </div>
</div>

        {% endfor %}
    </div>
</div>

<h1 align="center" >  <a class="btn btn-update" href="{% url 'movieapp:addmovie'  %}"> <b>Add Movies </b></a> </h1>>

{% endblock %}